# Основные метаданные сайта
site_name: Мой Блог
# site_url: https://musecollaboration.github.io/mkdocs-demo/
site_url: https://github.com/NikitaTichonow/mkdocs-demo.git
site_author: Nikita Tichonow

# Copyright в футере (только твой текст, без лишнего)
copyright: © 2026 Nikita Tichonow

# Тема оформления
theme:
  name: material
  language: ru

  # Цветовая палитра — тёмная тема по умолчанию + переключатель на светлую
  palette:
    # Тёмная (slate) — основная / по умолчанию
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7 # Солнышко — переключить на светлую
        name: Переключиться на светлую тему

    # Светлая — только как запасная опция
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4 # Луна — переключить на тёмную
        name: Переключиться на тёмную тему

  # Полезные функции темы
  # features:
  #   - navigation.sections
  #   - navigation.tracking
  #   - navigation.footer
  #   - toc.integrate
  #   - content.code.copy
  #   - content.code.annotate
  #   - search.suggest
  #   - search.highlight

# Ключевой блок: полностью убирает "Made with Material for MkDocs"
extra:
  generator: false # ← это удаляет надпись навсегда

  # Социальные иконки в футере справа (настрой свои ссылки)
  

# Репозиторий + кнопка "Редактировать"
repo_url: https://github.com/NikitaTichonow/mkdocs-demo.git
repo_name: NikitaTichonow/mkdocs-demo
edit_uri: edit/main/docs/

# Следить за изменениями
watch:
  - docs

# Навигация
nav:
  - Главная: index.md
  - Обо Мне: about.md